# Generated by Django 5.1.2 on 2024-11-05 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ChanguitasApi.direccion'),
        ),
    ]
