# Generated by Django 5.1.2 on 2024-11-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0002_categoria_cliente_direccion_fotos_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, upload_to='imagenesUsuario'),
        ),
    ]
