# Generated by Django 5.1.2 on 2024-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0003_alter_usuario_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=100),
        ),
    ]
