# Generated by Django 5.0.4 on 2024-12-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0004_alter_direccion_altura_alter_direccion_calle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='estado',
        ),
        migrations.AddField(
            model_name='servicio',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lun'), ('Martes', 'Mar'), ('Miércoles', 'Mie'), ('Jueves', 'Jue'), ('Viernes', 'Vie'), ('Sábado', 'Sab'), ('Domingo', 'Dom')], default='Lunes', max_length=10),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Iniciado', 'I'), ('Finalizado', 'F'), ('Cancelado', 'C')], default='Iniciado', max_length=15),
        ),
    ]
