# Generated by Django 5.0.4 on 2024-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0005_remove_servicio_estado_servicio_dia_servicio_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='hora',
            new_name='desdeHora',
        ),
        migrations.AddField(
            model_name='servicio',
            name='hastaHora',
            field=models.TimeField(default='00:00'),
        ),
    ]
