# Generated by Django 5.1.2 on 2024-12-03 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0006_rename_hora_servicio_desdehora_servicio_hastahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='fotos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedorservicio',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_ofrecidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaDisponible',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horarioDisponible',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_notificacion', to='ChanguitasApi.notificacion'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
