# Generated by Django 5.1.2 on 2024-12-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0007_alter_solicitud_cliente_remove_proveedor_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
