# Generated by Django 5.1.2 on 2024-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0008_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorservicio',
            name='fechaHasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaDisponible',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='horarioDisponible',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
