# Generated by Django 5.1.2 on 2024-12-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0009_alter_proveedorservicio_fechahasta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='servicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='categorias',
            field=models.ManyToManyField(related_name='servicios', to='ChanguitasApi.categoria'),
        ),
    ]
