# Generated by Django 5.1.2 on 2024-12-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0010_remove_categoria_servicio_servicio_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cantServiciosContratados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cantServiciosTrabajados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
