# Generated by Django 5.0.4 on 2025-01-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0011_usuario_cantservicioscontratados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(default='2000-01-01', verbose_name='fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='imagenesUsuario/empty.jpg', null=True, upload_to='imagenesUsuario'),
        ),
    ]
