# Generated by Django 5.0.4 on 2025-01-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChanguitasApi', '0012_alter_usuario_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, default=1234),
        ),
    ]
